CREATE DATABASE HospitalDB;
GO
USE HospitalDB;
GO
CREATE TABLE Pacientes (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 Nombre NVARCHAR(100) NOT NULL,
 Apellido NVARCHAR(100) NOT NULL,
 FechaNacimiento DATE NOT NULL,
 Telefono NVARCHAR(15) NOT NULL,
 Email NVARCHAR(100) UNIQUE NOT NULL,
 Direccion NVARCHAR(255) NOT NULL
);
CREATE TABLE Medicos (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 Nombre NVARCHAR(100) NOT NULL,
 Apellido NVARCHAR(100) NOT NULL,
 EspecialidadId INT NOT NULL,
 Telefono NVARCHAR(15) NOT NULL,
 Email NVARCHAR(100) UNIQUE NOT NULL
);
CREATE TABLE Especialidades (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 Nombre NVARCHAR(100) NOT NULL
);
CREATE TABLE Citas (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 PacienteId INT FOREIGN KEY REFERENCES Pacientes(Id),
 MedicoId INT FOREIGN KEY REFERENCES Medicos(Id),
 FechaHora DATETIME NOT NULL,
 Estado NVARCHAR(20) NOT NULL
);
CREATE TABLE Tratamientos (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 PacienteId INT FOREIGN KEY REFERENCES Pacientes(Id),
 Descripcion NVARCHAR(255) NOT NULL,
 Fecha DATE NOT NULL,
 Costo DECIMAL(10,2) NOT NULL
);
CREATE TABLE Facturacion (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 PacienteId INT FOREIGN KEY REFERENCES Pacientes(Id),
 Monto DECIMAL(10,2) NOT NULL,
 MetodoPago NVARCHAR(50) NOT NULL,
 FechaPago DATE NOT NULL
);